name: Minecraft Server

on:
  workflow_dispatch:   # allow manual start

jobs:
  minecraft:
    runs-on: windows-latest   # or ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Paper
        run: |
          curl -o paper.jar https://api.papermc.io/v2/projects/paper/versions/1.21.8/builds/70/downloads/paper-1.21.8-70.jar

      - name: Start Minecraft
        run: |
          java -Xmx2G -Xms2G -jar paper.jar nogui

      - name: Re-run workflow before timeout
        if: always()
        run: |
          curl -X POST ^
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ^
            -H "Accept: application/vnd.github+json" ^
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/mc-server.yml/dispatches ^
            -d "{\"ref\":\"main\"}"
