name: Minecraft Paper Server

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 * * * *' # optional: every hour

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Download Paper 1.21.8
      run: |
        mkdir -p server
        curl -o server/paper.jar https://api.papermc.io/v2/projects/paper/versions/1.21.8/builds/100/downloads/paper-1.21.8-100.jar

    - name: Run Minecraft Server
      run: |
        cd server
        echo "eula=true" > eula.txt
        java -Xms512M -Xmx1G -jar paper.jar nogui
